Update LinearSolverPetsc.cpp
In response to the following error:

/home/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp: In function 'void Opm::{anonymous}::solve_system(Opm::{anonymous}::OEM_DATA&, KSPType, PCType, double, double, double, int, int)':
/home/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:200:69: error: too many arguments to function 'PetscErrorCode KSPSetOperators(KSP, Mat, Mat)'
         KSPSetOperators( t.ksp, t.A, t.A, DIFFERENT_NONZERO_PATTERN );
                                                                     ^
In file included from /home/opm/petsc/include/petscsnes.h:6:0,
                 from /home/opm/petsc/include/petscts.h:7,
                 from /home/opm/petsc/include/petsc.h:26,
                 from /home/opm/opm-core/opm/core/linalg/LinearSolverPetsc.cpp:26:
/home/opm/petsc/include/petscksp.h:310:29: note: declared here
 PETSC_EXTERN PetscErrorCode KSPSetOperators(KSP,Mat,Mat);
                             ^
make[2]: *** [CMakeFiles/opmcore.dir/opm/core/linalg/LinearSolverPetsc.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/opmcore.dir/all] Error 2
make: *** [all] Error 2

UPDATE at line 200:
Signature to KSPSetOperators() changed from 4 parameters to 3, dropping out last parameter on NonZero Patterns.